// Code generated by MockGen. DO NOT EDIT.
// Source: investment_environment_score.go
//
// Generated by this command:
//
//	mockgen -source=investment_environment_score.go -package=mock -destination=./mock/investment_environment_score.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvestmentEnvironmentCalculator is a mock of InvestmentEnvironmentCalculator interface.
type MockInvestmentEnvironmentCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockInvestmentEnvironmentCalculatorMockRecorder
}

// MockInvestmentEnvironmentCalculatorMockRecorder is the mock recorder for MockInvestmentEnvironmentCalculator.
type MockInvestmentEnvironmentCalculatorMockRecorder struct {
	mock *MockInvestmentEnvironmentCalculator
}

// NewMockInvestmentEnvironmentCalculator creates a new mock instance.
func NewMockInvestmentEnvironmentCalculator(ctrl *gomock.Controller) *MockInvestmentEnvironmentCalculator {
	mock := &MockInvestmentEnvironmentCalculator{ctrl: ctrl}
	mock.recorder = &MockInvestmentEnvironmentCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvestmentEnvironmentCalculator) EXPECT() *MockInvestmentEnvironmentCalculatorMockRecorder {
	return m.recorder
}

// BAA10Y mocks base method.
func (m *MockInvestmentEnvironmentCalculator) BAA10Y(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BAA10Y", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BAA10Y indicates an expected call of BAA10Y.
func (mr *MockInvestmentEnvironmentCalculatorMockRecorder) BAA10Y(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BAA10Y", reflect.TypeOf((*MockInvestmentEnvironmentCalculator)(nil).BAA10Y), ctx)
}

// FEDFUNDS mocks base method.
func (m *MockInvestmentEnvironmentCalculator) FEDFUNDS(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FEDFUNDS", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FEDFUNDS indicates an expected call of FEDFUNDS.
func (mr *MockInvestmentEnvironmentCalculatorMockRecorder) FEDFUNDS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FEDFUNDS", reflect.TypeOf((*MockInvestmentEnvironmentCalculator)(nil).FEDFUNDS), ctx)
}

// T10YFF mocks base method.
func (m *MockInvestmentEnvironmentCalculator) T10YFF(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "T10YFF", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// T10YFF indicates an expected call of T10YFF.
func (mr *MockInvestmentEnvironmentCalculatorMockRecorder) T10YFF(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "T10YFF", reflect.TypeOf((*MockInvestmentEnvironmentCalculator)(nil).T10YFF), ctx)
}

// US10Y mocks base method.
func (m *MockInvestmentEnvironmentCalculator) US10Y(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "US10Y", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// US10Y indicates an expected call of US10Y.
func (mr *MockInvestmentEnvironmentCalculatorMockRecorder) US10Y(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "US10Y", reflect.TypeOf((*MockInvestmentEnvironmentCalculator)(nil).US10Y), ctx)
}

// USDINDEX mocks base method.
func (m *MockInvestmentEnvironmentCalculator) USDINDEX(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "USDINDEX", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// USDINDEX indicates an expected call of USDINDEX.
func (mr *MockInvestmentEnvironmentCalculatorMockRecorder) USDINDEX(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "USDINDEX", reflect.TypeOf((*MockInvestmentEnvironmentCalculator)(nil).USDINDEX), ctx)
}
