# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.23.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Display Go version
      run: go version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
